import { Theme, ThemePanel } from "@radix-ui/themes"
import "@radix-ui/themes/styles.css"
import { AppearanceSwitch } from "@repo/ui/AppearanceSwitch"
import type { Metadata } from "next"
import { ThemeProvider } from "next-themes"
import localFont from "next/font/local"
import "./globals.css"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="de" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class">
          <Theme accentColor="iris" grayColor="slate" radius="medium">
            {children}
            <ThemePanel defaultOpen={false} />
            <AppearanceSwitch />
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  )
}
